### ISSUE TITLE
Port 7777 is already in use

### ISSUE THREAD

**Issue by kensan73** [officefloor/OfficeFloor#1380]
Is there an easy way to choose a different port, maybe in the application.woof file?  I followed the first tutorial which went smoothly until I went to run the server

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/10583935/194714952-51a0c29a-24f5-4c16-a004-2c31ca90d494.png">

**Comment by sagenschneider** [comment]
Excuse us not getting back to you.

The 7777 port is used for JMX to control starting and stopping the OfficeFloor service.  You can configure another port for it via `jmxPort` property in the maven configuration to avoid port clash with existing running services.

See following for more information:
https://github.com/officefloor/OfficeFloor/blob/d1c3200d784abb201f2ae0137759640d34289722/officefloor/maven/officefloor-maven-plugin/src/main/java/net/officefloor/maven/OpenOfficeFloorMojo.java#L79
